app/urls.py
from django.urls import path, include
from . import views
from . views import CustomSignupView, CustomLoginView

urlpatterns = [
  path('', views.home, name="home"),
  path('about', views.about, name="about"),
  path('recommendations', views.recommendations, name="recommendations"),
  path('contact', views.contact, name="contact"),
  path('delete-account/', views.delete_account, name="delete_account"),

  # all_auth urls
  path('accounts/login/', CustomLoginView.as_view(), name='account_login'),
  path('accounts/signup/', CustomSignupView.as_view(), name='account_signup'),
  path('accounts/profile/<int:profile_id>', views.profile, name='profile'),
  path('accounts/profile/<int:profile_id>/settings', views.profile_settings, name='profile_settings'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

AGE_BAND_CHOICES = [
    ("rather_not_say", "Rather not say"),
    ("under_25", "Under 25"),
    ("25_to_35", "25 - 35"),
    ("36_and_over", "36 and over"),
]


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default="profile2.png", null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    friend_visibility = models.BooleanField(default=True, null=True)
    age_band = models.CharField(
        max_length=20, choices=AGE_BAND_CHOICES, null=True, blank=False, default='rather_not_say'
    )

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

app/templates/app/about.html
{% extends "app/main.html" %} {% load static %}{% block content %}

<style>
  .viewport-height {
    min-height: 70vh;
    overflow-y: auto;
  }
</style>

<!-- about body -->
<section>
  <div class="container">
    <div class="row">
      <div class="col viewport-height">
          <h1>About Socializer</h1>
          <p>
            Get amongst it with Socializer. Meet new people, attend cool events and explore our beautiful city 
          </p>
          <h4>Want to host?</h4>
          <p>
            Create an event at the top, supply event details including a description
            of the event. Done.
          </p>
          <h4>Attend Events</h4>
          <p>
            With so many cool events to choose from get amongst it!
          </p>
          <p>Sign up now <a href="{% url 'account_signup' %}">here</a>. Don't forget to upload a profile pic!</p>
      </div>
      </div>
    </div>
    
</section>

{% endblock %}

app/templates/app/contact.html
{% extends "app/main.html" %} {% block content %}

<section>
  <div class="container">
    <div class="row">
      <div class="col" style="height: 70vh;">
        <h1>Contact page</h1>
        <p>We value your feedback! You can get in touch with us at <a href="mailto:info@foodiefriend.com.au">info@foodiefriend.com.au</a></p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

app/templates/app/dashboard.html
{% extends "app/main.html" %} {% block content %} {% load static %}

<style>
  .empty-events {
  height: 80vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
}

.profile-pic{
		border-radius: 100%;
  	padding: 50px;
	}

/* .alert-fixed {
  position:fixed; 
  top: 0px; 
  left: 0px; 
  width: 100%;
  z-index:9999; 
  border-radius:0px;
  margin-top: 56px;
} */
</style>

<!-- messages -->
{% if messages %}
  <div>
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </div>
{% endif %}

<!-- showcase -->
{% if not request.user.is_authenticated %}
<section
  class="bg-dark text-light p-5 p-lg-0 pt-lg-5 text-center text-sm-start"
>
  <div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-2">
      <div>
        <h1>Meet, <span class="text-warning">Socialize,</span> Explore</h1>
        <p class="lead my-4">Let the good times roll with Socializer. Free for everyone.</p>
        <a
          href="{% url 'create' %}"
          class="btn btn-primary btn-lg"
        >
          Create My Event
      </a>
      </div>

      <img
        class="img-fluid w-50 d-none d-sm-block"
        src="images/having_fun.svg"
        alt=""
      />
    </div>
  </div>
</section>
{% endif %}

<!-- event cards -->
<section>
  <div class="container">
    
    {% if user.is_authenticated %}
      <h1>Hi, {{request.user.first_name }} 👋</h1>
    {% endif %}

    {% if events %}
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
      {% for event in events %}
      <div class="col">
        <div class="card">
          <h5 class="card-title p-2">{{ event.event_title }}</h5>
          {% if event.host.profile_pic %}
          <img
            src="{{ event.host.profile_pic.url }}"
            class="profile-pic"
            alt="{{ event.title }}"
          />
          {% else %}
          <img
            src="{% static 'images/profile2.png' %}"
            class="profile-pic"
            alt="{{ event.title }}"
          />
          {% endif %}
          <div class="card-body">
            <p class="card-text">{{ event.description|truncatechars:50 }}</p>
            <a href="{% url 'event' event.id %}" class="btn btn-primary"
              >Browse Event</a
            >
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <!-- Pagination links -->
    {% if events.has_other_pages %}
    <div class="pagination">
      {% if events.has_previous %}
      <a href="?page=1" class="page-link">&laquo; First</a>
      <a href="?page={{ events.previous_page_number }}" class="page-link"
        >&lsaquo; Previous</a
      >
      {% endif %}
      <span class="current-page"
        >Page {{ events.number }} of {{ events.paginator.num_pages }}</span
      >
      {% if events.has_next %}
      <a href="?page={{ events.next_page_number }}" class="page-link"
        >Next &rsaquo;</a
      >
      <a href="?page={{ events.paginator.num_pages }}" class="page-link"
        >Last &raquo;</a
      >
      {% endif %}
    </div>
    {% endif %} {% else %}
    <div class="empty-events">
      <h2>wow such empty ^-^</h2>
    </div>
    {% endif %}
  </div>
</section>


{% endblock %}

app/templates/app/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
            {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

        {% for message in messages %}

        <p id="messages">{{message}}</p>
        {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center links">
						Forgot password? <a href="#" class="ml-2">Reset password</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

app/templates/app/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Google tag (gtag.js) -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-GXS0PL1XJX"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-GXS0PL1XJX");
    </script>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Socializer</title>
    <!-- bootstrap imports -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <!-- flatpickr imports  -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"
    />
    <!-- native css imports -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>
  <style>
    .footer {
      background-color: #2b3034;
      height: 35vh;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
    }

    .footer h5 {
      color: white;
    }

    .footer p {
      color: white;
    }

    @media (min-width: 768px) {
      .news-input {
        width: 50%;
      }
    }
  </style>
  <body class="bg-light">
    {% include 'app/navbar.html' %} {% block content %} {% endblock%}

    <footer class="footer text-center mt-5">
      <div class="container">
        <h5 class="mb-3">
          &copy; <span id="currentYear"></span> Socializer. All rights
          reserved.
        </h5>
        <p class="mb-3">Sydney, NSW, Australia</p>
        <p><a class="text-decoration-none" href="{% url 'contact' %}">Contact Us</a></p>
        <p><a class="text-decoration-none"href="{% url 'about' %}">About</a></p>
        <p><a class="text-decoration-none" href="{% url 'recommendations' %}">Recommendations</a></p>
      </div>
    </footer>
    <script>
      var currentYear = new Date().getFullYear();
      document.getElementById("currentYear").textContent = currentYear;
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/app/navbar.html
{% load static %}

<style>
  .logo {
    letter-spacing: 0.2em;
    color: transparent;
    font-style: italic;
    transform: skew(-10deg);
  }
</style>

<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container">
    <!-- Logo -->
    <a class="nav-link text-white me-3 fw-bold fs-5 logo" href="{% url 'home' %}">/ SOCIALIZER /</a>

    <!-- Notification Bell -->
    {% if request.user.is_authenticated %}
      <a class="nav-link d-lg-none ms-auto" href="{% url 'notifications' %}">
        🔔
        {% if unread_count > 0 %}
          <span class="badge bg-danger rounded-circle">{{ unread_count }}</span>
        {% endif %}
      </a>
    {% endif %}

    <!-- Hamburger Button -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Leftside Nav Links -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Events</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create' %}">Create Event</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recommendations' %}">Recommendations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
      </ul>

      <!-- Right side Nav Links -->
      <ul class="navbar-nav ms-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item d-none d-lg-block">
          <a class="nav-link" href="{% url 'notifications' %}">
            🔔
            {% if unread_count > 0 %}
              <span class="badge bg-danger rounded-circle">{{ unread_count }}</span>
            {% endif %}
          </a>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'messages' request.user.profile.id %}">Messages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' request.user.profile.id %}">Profile</a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
          </li>
          
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

app/templates/app/profile.html
{% extends "app/main.html" %}
{% block content %}
{% load account %}
{% load static %}

<style>
	.profile-pic {
		max-width: 200px;
		max-height: 200px;
		margin: 0 auto;
		border-radius: 50%;
	}

	.avatar {
		width: 50px;
		border-radius: 100%;
		margin-right: 5px;
		object-fit: cover;
	}

	.gallery {
		display: flex;
		flex-wrap: wrap;
		justify-content: space-between;
	}

	.gallery-item {
		flex: 50px 50px 50px 50px;
		/* Adjust the width of each column as needed */
		margin-bottom: 20px;
		background-color: brown;
	}

	.gallery-item img {
		max-width: 100%;
		height: auto;
	}

	/* .alert-fixed {
    position:fixed; 
    top: 0px; 
    left: 0px; 
    width: 100%;
    z-index:9999; 
    border-radius:0px;
		margin-top: 56px;
} */

	.profile-albums {
		max-width: 45%;
	}

	hr.style-one {
		border: 0;
		height: 1px;
		background: #333;
		background-image: linear-gradient(to right, #ccc, #333, #ccc);
	}

	.placeholder-italic::placeholder {
		font-style: italic;
	}
</style>

<section>
	<div class="container mt-2">
		{% if messages %}
		<div>
			{% for message in messages %}
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			{% endfor %}
		</div>
		{% endif %}
		<div class="row">

			<!-- column 1 -->
			<div class="col-md">
				<!-- user name and profile image -->
				<div class="card card-body mb-2">
					<form action="#" method="post" class="w-100">
						{% if request.user.profile != profile %}
						{% csrf_token %}
						{% if button == "Add" %}
						<form action="#" method="post" class="w-100">
							{% csrf_token %}
							<button class="btn btn-primary w-100" name="friend-button" value="Add">
								Add Friend
							</button>
						</form>
						{% elif button == "Pending" %}
						{% csrf_token %}
						<button disabled class="btn btn-danger w-100" name="friend-button" value="Pending">
							Friend Request Pending
						</button>
						{% elif button == "Accepted" %}
						<p>You and {{ profile.user.first_name }} are friends</p>
						{% endif %}
						{% endif %}
					</form>
					<!-- message button -->
					{% if request.user.profile != profile %}
					{% if is_friend %}
					<a class="btn btn-warning mt-2" href="#" data-bs-toggle="modal" data-bs-target="#reg-modal">Message</a>
					{% else %}
					<a class="btn btn-warning mt-2" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">Message</a>
					{% endif %}
					{% else %}
					<!-- user settings link -->
					<a href="{% url 'profile_settings' profile.id %}" class="btn btn-warning w-100 mt-2">User settings</a>
					{% endif %}
					<hr class="style-one" />
					<h3 style="text-align: center">
						{{ profile.user.first_name }} {{profile.user.last_name|slice:":1" }}
					</h3>
					<hr class="style-one" />
					{% if profile.profile_pic %}
					<img class="profile-pic" src="{{profile.profile_pic.url}}" />
					{% else %}
					<img class="profile-pic" src="{% static 'images/profile2.png' %}" alt="Default Profile Picture" />
					{% endif %}



				</div>
				{% if request.user.profile == profile %}
				<!-- profile pic form -->
				<div class="card card-body mb-2">
					<form method="POST" action="" enctype="multipart/form-data">
						{% csrf_token %}
						{{profile_form.as_p}}

						<input class="btn btn-primary" type="submit" name="profile-pic" value="update-image">
					</form>

				</div>

				<!-- profile description -->
				<div class="card card-body mb-2">
					<form method="POST" action="">
						{% csrf_token %}
						{{ description_form.as_p }}
						<button class="btn btn-primary mt-2" type="submit" name="update-description">Update About</button>
					</form>
				</div>
				{% else %}
				<!-- display age band and description as plain text -->
				<div class="card card-body mb-2">
					{% if profile.description %}
						<h4>About Me</h4>
						<p>{{ profile.description }}</p>
					{% endif %}
					<h4>Age Band</h4>
					<p>{{ profile.get_age_band_display }}</p>
				</div>


				{% endif %}
			</div>


			<!-- column 2 -->
			<div class="col-md">
				<div class="card card-body mb-2">
					<div>
						<a class="mb-3 d-inline-block text-decoration-none" href="{% url 'friends' profile.id %}">
							<h1>Friends {% if friends.count > 0 and friend_visibility %} ({{ friends.count }}) {% endif %}</h1>
						</a>
						<ul class="list-unstyled">
							{% if friends %}
							{% for friend in friends %}
							<li class="mb-2">
								<a href="{% url 'profile' friend.id %}" class="text-decoration-none">
									{% if friend.profile_pic %}
									<img class="avatar" src="{{ friend.profile_pic.url }}" alt="Avatar">
									{% else %}
									<img class="avatar" src="{% static 'images/default_profile_pic.png' %}" alt="Avatar">
									{% endif %}
									{{ friend.user.first_name }}
								</a>
							</li>
							<hr class="style-one">
							{% endfor %}
							{% else %}
							<p><em>No friends showing</em></p>
							{% endif %}
						</ul>
						{% if request.user.profile == profile %}
						<a href="{% url 'friend_requests' profile.id %}" class="btn btn-primary w-100">Friend Requests</a>
						{% endif %}
					</div>
				</div>

				<div class="card card-body mb-2">
					<div>
						<h1>Events Attending</h1>
						<ul class="list-unstyled">
							{% for event in attended_events %}
							{% if not event.cancelled %}
							<li><a href="{% url 'event' event.id %}" class="text-decoration-none"><img class="avatar"
										src="{{ event.host.profile_pic.url }}" alt="Avatar">{{ event.event_title }}</a></li>
							<hr class="style-one">
							{% else %}
							<li><em>No events hosting</em></li>
							{% endif %}
							{% empty %}
							<li><em>No events attending</em></li>
							{% endfor %}
						</ul>

						<h1 class="mt-5">Events Hosting </h1>
						<ul class="list-unstyled">
							{% for event in hosted_events %}
							{% if not event.cancelled %}
							<li>
								<a href="{% url 'event' event.id %}" class="text-decoration-none">
									<img class="avatar" src="{{ event.host.profile_pic.url }}" alt="Avatar">
									{{ event.event_title }}
								</a>
							</li>
							<hr class="style-one">
							{% else %}
							<li><em>No events hosting</em></li>
							{% endif %}
							{% empty %}
							<li><em>No events hosting</em></li>
							{% endfor %}
						</ul>
						{% if request.user.profile == profile %}
						<a href="{% url 'event_requests' profile.id %}" class="btn btn-primary w-100">Event Requests</a>
						{% endif %}
					</div>
				</div>



			</div>





			<!-- column 3 -->

			<div class="col-md mb-2">
				<div class="card card-body">
					<div>
						<h1><a href="{% url 'gallery' profile.id %}" class="text-decoration-none">{{ profile.user.first_name }}'s
								Photo Gallery</a></h1>
						{% if user_photos %}
						{% for photo in user_photos %}
						<a href="{% url 'gallery' profile.id %}"><img src="{{photo.image.url}}" alt=""
								class="profile-albums mb-2"></a>
						{% endfor %}
						{% else %}
						<p><em>User has not yet uploaded any photos</em></p>
						{% endif %}
					</div>
				</div>

				{% if request.user.profile == profile %}
				<!-- Invite Friend Form -->
        <section>
          <h3>Invite a Friend To Socializer</h3>
          <form method="post" action="">
            {% csrf_token %}
            {{ invite_friend_form.as_p }}
            <button type="submit" name="invite-friend" class="btn btn-primary">Send Invitation</button>
          </form>
        </section>
        <!-- end invite friend form -->
				{% endif %}
			</div>
			<!-- end column 3 -->



		</div>
	</div>

	<!-- messaging modal -->
	<div class="modal fade" id="reg-modal" tabindex="-1" aria-labelledby="modal-title" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="modal-title">Send a message to {{ profile.user.first_name }}</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<form method="post" action="{% url 'send_message' profile.id %}">
						{% csrf_token %}
						<div class="form-group">
							<label for="message-text" class="col-form-label">Message:</label>
							<textarea class="form-control" id="message-text" name="message" required></textarea>
						</div>
						<button type="submit" class="btn btn-primary mt-2">Submit</button>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- end -->

	<!-- DM not friend modal -->
	<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="exampleModalLabel">Only Friends Can Message</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					Please send a friend request to {{ profile.user.first_name }}
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>

	<!-- end -->


</section>

{% endblock %}